"""initial

Revision ID: 1cb5ba355d7f
Revises: 
Create Date: 2026-03-19 19:54:20.831418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb5ba355d7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('circle_wallet_id', sa.String(length=128), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('arc_registry_tx', sa.String(length=66), nullable=True),
    sa.Column('is_registered_on_chain', sa.Boolean(), nullable=False),
    sa.Column('total_earned_usdc', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name'),
    sa.UniqueConstraint('circle_wallet_id')
    )
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('parsed_jd', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_spent_usdc', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('escrow_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('refund_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('recruiter_wallet_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('apollo_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('github_username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('email_confidence', sa.Integer(), nullable=True),
    sa.Column('email_status', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('github_profile', sa.JSON(), nullable=True),
    sa.Column('github_repos', sa.JSON(), nullable=True),
    sa.Column('github_score', sa.Float(), nullable=True),
    sa.Column('skill_match_pct', sa.Float(), nullable=True),
    sa.Column('seniority_fit', sa.String(length=16), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('rank_justification', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('paying_agent', sa.String(length=64), nullable=False),
    sa.Column('receiving_agent', sa.String(length=64), nullable=False),
    sa.Column('amount_usdc', sa.Float(), nullable=False),
    sa.Column('arc_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('x402_payment_proof', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_logs')
    op.drop_table('candidates')
    op.drop_table('searches')
    op.drop_table('agent_wallets')
    # ### end Alembic commands ###
